import { useEffect, useState, type ReactNode } from 'react';
import { Link, NavLink, Route, Routes } from 'react-router-dom';
import './editorial-fixes.css';

const wa='https://wa.me/5541992635906';
const shop='https://saiajustavestidos.com.br';

function Reveal({children,delay=''}:{children:ReactNode;delay?:string}){const [show,setShow]=useState(false);useEffect(()=>{setShow(true)},[]);return <div className={`reveal ${delay} ${show?'visible':''}`}>{children}</div>}
function Header(){const [open,setOpen]=useState(false);return <><div className="announcement"><span>26 anos vestindo momentos inesquecíveis</span><a href="#colecao">Descubra a coleção ↗</a></div><header className="site-header"><Link className="brand" to="/"><span className="brand-mark"><i/><i/></span><span>SAIA JUSTA<small>VESTIDOS</small></span></Link><nav className={`desktop-nav ${open?'mobile-open':''}`}><NavLink to="/#colecao" onClick={()=>setOpen(false)}>Coleção</NavLink><NavLink to="/#experiencia" onClick={()=>setOpen(false)}>A experiência</NavLink><NavLink to="/#categorias" onClick={()=>setOpen(false)}>Ocasiões</NavLink><NavLink to="/#loja" onClick={()=>setOpen(false)}>A loja</NavLink></nav><a className="header-cta" href={wa} target="_blank" rel="noreferrer">Falar com uma consultora ↗</a><button className="menu-button" aria-label="Abrir menu" aria-expanded={open} onClick={()=>setOpen(!open)}><span/><span/></button></header></>}
function Home(){return <><Header/><main><section className="hero"><Reveal><div className="hero-copy"><p className="eyebrow">CURITIBA · ENVIO PARA TODO O BRASIL</p><h1>O vestido certo<br/><em>muda tudo.</em></h1><p className="hero-text">Para o evento, para a foto, para a memória. Uma curadoria de vestidos de festa pensada para você se sentir <strong>inesquecível.</strong></p><div className="hero-actions"><a className="button button-dark" href="#colecao">Ver vestidos ↓</a><a className="text-link" href={wa} target="_blank" rel="noreferrer">Quero ajuda para escolher ↗</a></div><div className="hero-note"><span className="rating">★</span><span><strong>4,7/5</strong> · 295 avaliações</span><span className="dot"/><span>Rua Atílio Bório, 1828</span></div></div></Reveal><Reveal delay="delay-1"><div className="hero-visual"><div className="hero-image image-a"/><div className="hero-image image-b"/><div className="hero-stamp"><span>SAIA<br/>JUSTA</span><small>EST. 1998</small></div><div className="vertical-label">MADRINHAS · MÃES · CONVIDADAS</div></div></Reveal></section><div className="marquee"><div>VESTIDOS DE FESTA <span>✦</span> MADRINHAS <span>✦</span> MÃES DOS NOIVOS <span>✦</span> CONVIDADAS <span>✦</span> PLUS SIZE <span>✦</span> VESTIDOS DE FESTA <span>✦</span></div></div><Collection/><Categories/><Experience/><section className="quote-section"><div className="quote-mark">“</div><blockquote>O vestido perfeito não é só o que veste bem.<br/><em>É o que faz você se reconhecer no espelho.</em></blockquote><div className="quote-line"/><p>SAIA JUSTA VESTIDOS · CURITIBA</p></section><Store/></main><Footer/></>}
function Collection(){return <section className="collection section" id="colecao"><div className="section-head"><div><p className="eyebrow">A NOVA CURADORIA</p><h2>Para chegar e <em>parar tudo.</em></h2></div><a className="text-link" href={shop} target="_blank" rel="noreferrer">Ver loja online ↗</a></div><div className="editorial-grid"><article className="look-card look-tall"><div className="look-image dress-one"/><div className="look-info"><span>01 / 04</span><h3>Elegância sem esforço</h3><p>Silhuetas que acompanham o movimento.</p></div></article><article className="look-card"><div className="look-image dress-two"/><div className="look-info"><span>02 / 04</span><h3>Cor que fala por você</h3><p>Do delicado ao marcante.</p></div></article><article className="look-card"><div className="look-image dress-three"/><div className="look-info"><span>03 / 04</span><h3>O detalhe é tudo</h3><p>Texturas, brilho e acabamento.</p></div></article></div></section>}
function Categories(){const cards=[['01','Madrinhas','Para estar ao lado de quem você ama.','cat-madrinhas','category-large'],['02','Mães dos noivos','Presença à altura do momento.','cat-maes',''],['03','Convidadas','Seu evento. Seu estilo.','cat-convidadas',''],['04','Plus size','Mais opções, mais liberdade para escolher.','cat-plus','category-dark']];return <section className="categories section" id="categorias"><div className="section-head"><div><p className="eyebrow">ENCONTRE O SEU</p><h2>Uma ocasião.<br/><em>Mil possibilidades.</em></h2></div><p className="section-intro">Você conta o evento. A gente cuida do resto — modelo, cor, caimento e aquele “é esse!” que acontece na frente do espelho.</p></div><div className="category-grid">{cards.map(([n,title,text,bg,extra])=><a className={`category ${extra}`} href={wa} target="_blank" rel="noreferrer" key={title}><div className={`cat-bg ${bg}`}/><div className="cat-shine"/><div className="cat-content"><span>{n}</span><h3>{title}</h3><p>{text}</p></div><div className="cat-orb" aria-hidden="true"/><b>↗</b></a>)}</div></section>}
function Experience(){return <section className="experience section" id="experiencia"><div className="experience-photo"><div className="experience-caption"><span>DESDE 1998</span><strong>26 anos de histórias<br/>vestidas de festa.</strong></div><div className="experience-float">✦<small>FEITO PARA<br/>VOCÊ</small></div></div><div className="experience-copy"><p className="eyebrow">A EXPERIÊNCIA SAIA JUSTA</p><h2>Você não precisa saber qual vestido quer.</h2><p>A gente entende de vestido. E entende que escolher um look para uma ocasião importante pode dar frio na barriga. Por isso, nosso atendimento começa ouvindo você.</p><div className="steps"><div><span>01</span><p><strong>Você conta.</strong><br/>Evento, horário, estilo e o que você quer sentir.</p></div><div><span>02</span><p><strong>A gente seleciona.</strong><br/>Modelos, cores e tamanhos que fazem sentido.</p></div><div><span>03</span><p><strong>Você experimenta.</strong><br/>Até encontrar aquele que parece ter sido feito para você.</p></div></div><a className="button button-outline" href={wa} target="_blank" rel="noreferrer">Agendar atendimento ↗</a></div></section>}
function Store(){return <section className="store section" id="loja"><div className="store-copy"><p className="eyebrow">VENHA NOS CONHECER</p><h2>Seu próximo vestido<br/><em>começa aqui.</em></h2><div className="store-details"><p><strong>Rua Atílio Bório, 1828</strong><br/>Hugo Lange · Curitiba/PR<br/><span>Confira o horário antes de vir</span></p><p><strong>(41) 99263-5906</strong><br/>Atendimento e pedidos pelo WhatsApp</p></div><div className="store-actions"><a className="button button-dark" href="https://www.google.com/maps/search/?api=1&query=Rua+Atílio+Bório+1828+Curitiba+PR" target="_blank" rel="noreferrer">Como chegar ↗</a><a className="button button-light" href={shop} target="_blank" rel="noreferrer">Comprar online ↗</a></div></div><div className="store-map"><div className="map-grid"/><div className="map-pin"><span>SAIA<br/>JUSTA</span></div><div className="map-address">R. ATÍLIO BÓRIO, 1828<br/><small>CURITIBA · PR</small></div></div></section>}
function Footer(){return <footer><div className="footer-top"><Link className="brand brand-footer" to="/"><span className="brand-mark"><i/><i/></span><span>SAIA JUSTA<small>VESTIDOS</small></span></Link><div className="footer-message">O vestido certo<br/><em>muda tudo.</em></div><div className="footer-links"><a href="https://www.instagram.com/saiajustavestidos" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.facebook.com/saiajustavestidos" target="_blank" rel="noreferrer">Facebook ↗</a><a href={shop} target="_blank" rel="noreferrer">Loja online ↗</a></div></div><div className="footer-bottom"><span>© 2026 Saia Justa Vestidos</span><span>Curitiba · Paraná · Brasil</span><Link to="/">Voltar ao topo ↑</Link></div></footer>}
function Placeholder({title}:{title:string}){return <><Header/><main className="page-placeholder"><p className="eyebrow">SAIA JUSTA VESTIDOS</p><h1>{title}</h1><p>Esta área está pronta para receber a próxima experiência da loja.</p><Link className="button button-dark" to="/">Voltar para a home ↗</Link></main><Footer/></>}
export default function App(){return <><Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Placeholder title="Login"/>}/><Route path="/dashboard" element={<Placeholder title="Dashboard"/>}/><Route path="/configuracoes" element={<Placeholder title="Configurações"/>}/><Route path="*" element={<Placeholder title="Página não encontrada"/>}/></Routes><a className="floating-whatsapp" href={wa} target="_blank" rel="noreferrer">WhatsApp · falar com a gente ↗</a></>}
